### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by yoohaemin** [stripe/dagon#43]
Hi, first of all, thank you for this great library, it seems like a perfect fit for a personal project I've been working on.
I am very interested in a version with 2.13 support, which I have done some work at my fork.

The build migrations are almost done, but the `Stream` collection used in `Dag.scala` and `HMap.scala` conflicts with 2.13 collections update. From what I've seen, even `collections-compat` does not provide backported `LazyList` in older versions. 
 
Would it be ok to open a PR with fatal-warnings off for 2.13?

**Comment by johnynek** [comment]
I think @non is working on this and we should have something very soon.

A PR would be great if you have time though. The trick I think we want to do is to use scala-version specific build to keep using `Stream` on `2.12` but only use `LazyList` on `2.13`.

**Comment by non** [comment]
See #49

**Comment by non** [comment]
Version 0.3.3 does have 2.13 support. We need to update the README then we can close this.

**Comment by yoohaemin** [comment]
Wow, thank you very much for the quick resolution!
